name: MacOS-Tailscale-SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Tailscale
        run: |
          brew update
          brew install tailscale

      - name: Start Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscaled --tun=userspace-networking &
          sleep 5
          sudo tailscale up --authkey=$TAILSCALE_AUTHKEY --hostname=github-mac-vnc

      - name: Enable SSH
        run: |
          sudo systemsetup -setremotelogin on

      - name: Create SSH key access
        run: |
          mkdir -p /Users/runneradmin/.ssh
          ssh-keygen -t rsa -N "" -f /Users/runneradmin/.ssh/id_rsa

          cat /Users/runneradmin/.ssh/id_rsa.pub >> /Users/runneradmin/.ssh/authorized_keys

          chmod 700 /Users/runneradmin/.ssh
          chmod 600 /Users/runneradmin/.ssh/authorized_keys

      - name: Show connection info
        run: |
          echo "=============================="
          echo "TAILSCALE IP:"
          /usr/bin/tailscale ip -4 || true
          echo ""
          echo "SSH COMMAND:"
          echo "ssh -i ~/.ssh/id_rsa runneradmin@100.x.x.x"
          echo "=============================="

      - name: Keep alive
        run: |
          sleep 14400
