name: MacOS-VNC-Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Tailscale (via brew - stable on GitHub)
        run: |
          brew update
          brew install tailscale

      - name: Start Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscaled --tun=userspace-networking &
          sleep 5
          sudo tailscale up --authkey=$TAILSCALE_AUTHKEY --hostname=github-mac-vnc

      - name: Enable SSH
        run: |
          sudo systemsetup -setremotelogin on

      - name: Enable VNC
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on -users runneradmin -privs -all

          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -restart -agent

      - name: Show Tailscale IP
        run: |
          tailscale ip -4 || true

      - name: Keep Alive
        run: |
          sleep 14400
